name: sponge_client_angular_dart_example
description: The example of the Sponge client for Dart in the AngularDart web application.
version: 1.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  sponge_client_dart: ^1.7.0 

# The Sponge client uses a newer version of quiver than Angular.
dependency_overrides:
  quiver: '2.0.0+1'

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
